require 'rspec'
require 'pry'
require 'selenium-webdriver'
require 'capybara'

require_relative '../env/common_variables'
require_relative '../drivers/driver'
require_relative '../pages/base_page'
require_relative '../pages/cart_page'
require_relative '../pages/items_page'
